/**
 * The deterministic coverage audit (no AI): parse the glossary table, count how
 * often each term actually occurs in this volume's source (substring matching — the
 * correct semantics for Japanese), and report the zero-occurrence terms. The AI
 * validator's completeness check is the complementary judgment-based half.
 *
 * Part of the glossary.js layer (split out of the original single file).
 */

require("dotenv").config();
const fs = require("fs").promises;
const path = require("path");
require("../types"); // JSDoc type definitions

const { parseGlossaryTableTerms } = require("./carry-forward");

/**
 * Count (non-overlapping) occurrences of a term in a source text.
 *
 * Substring matching is the correct semantics for Japanese (no word
 * boundaries) and works for any script; glossary terms are proper nouns, so
 * the few false positives from shorter embedded terms are acceptable for a
 * coverage audit.
 *
 * @param {string} sourceText - The whole-volume source text.
 * @param {string} term - The source-language term to count.
 * @returns {number} The occurrence count.
 */
function countTermOccurrences(sourceText, term) {
  if (!sourceText || !term || typeof sourceText !== "string" || typeof term !== "string") {
    return 0;
  }
  let count = 0;
  let idx = sourceText.indexOf(term);
  while (idx !== -1) {
    count++;
    idx = sourceText.indexOf(term, idx + Math.max(1, term.length));
  }
  return count;
}


/**
 * Build the glossary coverage report (pure — testable without the filesystem).
 *
 * @param {{seriesName: string, installmentNumber: string, entries: Array<{term: string, section: string}>, sourceText: string}} p
 * @returns {string} The Markdown report.
 */
function buildGlossaryCoverageReportMarkdown({ seriesName, installmentNumber, entries, sourceText }) {
  const rows = [];
  const zeroTerms = [];
  for (const e of entries) {
    const count = countTermOccurrences(sourceText, e.term);
    rows.push(`| ${e.term} | ${e.section || "—"} | ${count} |`);
    if (count === 0) zeroTerms.push(e);
  }
  const lines = [];
  lines.push(`# Glossary Coverage — ${seriesName}, Volume ${installmentNumber}`);
  lines.push("");
  lines.push(
    "_Deterministic audit: each glossary term's occurrence count in this volume's source text " +
      "(substring match — the correct semantics for Japanese). Generated by the glossary task; no AI involved. " +
      "A zero-occurrence term is a candidate for a hallucinated entry or a term this volume no longer uses; " +
      "the AI validator's completeness check (terms present in the source but missing from the glossary) is " +
      "the complementary, judgment-based half of this audit._"
  );
  lines.push("");
  lines.push(`## Term occurrences (${entries.length} glossary terms)`);
  lines.push("");
  lines.push("| Term | Section | Occurrences |");
  lines.push("|---|---|---|");
  if (rows.length === 0) {
    lines.push("| (no terms parsed from the glossary) | — | — |");
  } else {
    lines.push(...rows);
  }
  lines.push("");
  lines.push("## Terms with zero occurrences");
  lines.push("");
  if (zeroTerms.length === 0) {
    lines.push("(none — every glossary term appears in this volume's source)");
  } else {
    for (const e of zeroTerms) lines.push(`- ${e.term} (${e.section || "—"})`);
  }
  lines.push("");
  return lines.join("\n");
}


/**
 * Write the deterministic term-coverage report for one volume
 * (glossary-coverage.md) — no AI call. Runs after the glossary is accepted
 * (and on the skip path, to keep the report fresh when the source changes).
 *
 * Best-effort by design: this audit is supplementary, so a failure is logged
 * as a warning and never fails an already-accepted volume.
 *
 * @param {GlossaryVolumeCtx} ctx - The volume context (must include bundle,
 *   glossaryOutputFile, values).
 * @returns {Promise<void>}
 */
async function writeGlossaryCoverageReport(ctx) {
  const { values, volumeDir, bundle, glossaryOutputFile } = ctx;
  const reportFile = path.join(volumeDir, "glossary-coverage.md");
  const jsonFile = path.join(volumeDir, "glossary-coverage.json");
  try {
    const glossaryContent = await fs.readFile(glossaryOutputFile, "utf-8");
    const sourceText = await fs.readFile(bundle.wholePath, "utf-8");
    const entries = parseGlossaryTableTerms(glossaryContent);
    const report = buildGlossaryCoverageReportMarkdown({
      seriesName: values.SOURCE_NAME,
      installmentNumber: values.INSTALLMENT_NUMBER,
      entries,
      sourceText,
    });
    await fs.writeFile(reportFile, report, "utf-8");
    // Machine-readable sidecar (same data as the Markdown table) — the
    // translation stage can load it for per-term "used in this volume" lookups
    // without parsing Markdown.
    await fs.writeFile(
      jsonFile,
      JSON.stringify(
        {
          seriesName: values.SOURCE_NAME,
          volume: values.INSTALLMENT_NUMBER,
          terms: entries.map((e) => ({
            term: e.term,
            section: e.section || null,
            occurrences: countTermOccurrences(sourceText, e.term),
          })),
        },
        null,
        2
      ) + "\n",
      "utf-8"
    );
    const zero = entries.filter((e) => countTermOccurrences(sourceText, e.term) === 0).length;
    console.log(
      `Volume ${values.INSTALLMENT_NUMBER}: glossary coverage report written ` +
        `(${entries.length} terms, ${zero} with zero occurrences) → ${reportFile} + ${path.basename(jsonFile)}`
    );
  } catch (err) {
    console.warn(
      `Volume ${values.INSTALLMENT_NUMBER}: could not write the glossary coverage report ` +
        `(${err.message}) — continuing.`
    );
  }
}

// ─── Export for use as a module ─────────────────────────────────────────────


module.exports = {
  countTermOccurrences,
  buildGlossaryCoverageReportMarkdown,
  writeGlossaryCoverageReport,
};
