/**
 * translation-qa.md — including the reference material the model did NOT see, because a stage that silently truncated the glossary was a stage that silently ignored terminology law (gotcha 43).
 *
 * Part of the translate.js layer (split out of the original single file).
 */

require("dotenv").config();
require("../types"); // JSDoc type definitions
const {
  sha256,
  splitChapter,
  buildTranslationTaskLines,
  buildTranslationPrompt,
  checkTranslationQa,
  mergeVolumeTranslation,
  resolvePublishedChapterTexts,
  findMissingSegments,
  stripMarkdownFence,
  tailOf,
  loadTranslationState,
  saveTranslationState,
  roleEndpoint,
  describeEndpoint,
  loadVolumeReferences,
  chapterTerminology,
  glossaryBlockMaxChars,
  stripContinuityOverlap,
  chapterArtifactNames,
  readFileOrEmpty,
  previousVolumeTail,
  buildBudgetedTaskLines,
  logRunEstimate,
  countStageChapters,
  checkChapterListConsistency,
  calibrateStageTokens,
  EMPTY_SOURCE_CHARS,
  loadVerificationSidecar,
  verdictCoversCurrentDraft,
  chapterContextHash,
  unverifiedMarker,
  recordBestDraft,
  STATE_FILE,
  QA_REPORT_FILE,
  MERGED_FILE,
  VERIFICATION_FILE,
  buildPolishGuardFindings,
  planChapterSplit,
  translateChunkCap,
  outputRatioFor,
  thinkingOutputFactor,
  measureOutputRatio,
  estimateTokens,
} = require("../utils/translate");

/**
 * Build one QA-report row for a chapter (re-runs the deterministic checks on
 * the given text — the report is always in sync with the files on disk).
 *
 * @param {{id: string, title: string}} seg
 * @param {string} sourceText
 * @param {string} draftText
 * @param {{terms: Array<{term: string, rendering: string}>}} refs
 * @param {string|string[]} statusOrWarnings - A status string (skipped) or
 *   the warnings array from the chapter's own QA run.
 * @returns {{id: string, title: string, status: string, ok: boolean, cjk: number, lengthRatio: number, warnings: string[]}}
 */
function buildQaRow(seg, sourceText, draftText, refs, statusOrWarnings, sourceLanguage, targetLanguage) {
  const qa = checkTranslationQa({ sourceText, draftText, terms: refs.terms, sourceLanguage, targetLanguage });
  const status =
    typeof statusOrWarnings === "string"
      ? statusOrWarnings
      : qa.warnings.length > 0
        ? "translated — with warnings"
        : "translated";
  const warnings = typeof statusOrWarnings === "string" ? qa.warnings : statusOrWarnings;
  return {
    id: seg.id,
    title: seg.title,
    status,
    ok: qa.ok,
    cjk: qa.cjk,
    lengthRatio: qa.lengthRatio,
    warnings,
  };
}


/**
 * Build the per-volume deterministic QA report (translation-qa.md).
 *
 * @param {{installmentNumber: string, folder: string}} volume
 * @param {Array<{id: string, title: string, status: string, ok: boolean, cjk: number, lengthRatio: number, warnings: string[]}>} qaRows
 * @returns {string} The Markdown report.
 */
function buildQaReportMarkdown(volume, qaRows, promptDrops = []) {
  const lines = [];
  lines.push(`# Translation QA — Volume ${volume.installmentNumber} (${volume.folder})`);
  lines.push("");
  lines.push(
    "_Deterministic audit of the chapter drafts (no AI): residual CJK ratio, length ratio vs the " +
      "source, and glossary-term coverage. CJK > 5% or an empty draft fails the chapter; CJK > 0.5%, " +
      "length ratio outside 0.6–2.5, and missing glossary renderings are warnings. Generated by the " +
      "translate task; refreshed on every run (including skipped chapters)._"
  );
  lines.push("");
  lines.push("| Chapter | Title | Status | CJK % | Length ratio | Warnings |");
  lines.push("|---|---|---|---|---|---|");
  for (const row of qaRows) {
    lines.push(
      `| ${row.id} | ${row.title || "—"} | ${row.ok ? row.status : row.status + " — FAILED"} | ` +
        `${(row.cjk * 100).toFixed(2)} | ${Number.isFinite(row.lengthRatio) ? row.lengthRatio.toFixed(2) : "n/a"} | ` +
        (row.warnings.length > 0 ? row.warnings.join("; ") : "—") +
        " |"
    );
  }
  lines.push("");
  const failed = qaRows.filter((r) => !r.ok);
  if (failed.length > 0) {
    lines.push(`**${failed.length} chapter(s) FAILED deterministic QA.**`);
    lines.push("");
  }
  if (promptDrops.length > 0) {
    lines.push("## Reference material the model did NOT see");
    lines.push("");
    lines.push(
      "_These chapters' prompts were trimmed to fit the model's context window. A chapter translated " +
        "without a block it should have had is a known limitation of that draft, not a hidden detail._"
    );
    lines.push("");
    lines.push("| Chapter | Part | Dropped |");
    lines.push("|---|---|---|");
    for (const d of promptDrops) {
      lines.push(
        `| ${d.id} | ${d.part} | ${d.dropped.map((x) => `${x.name} (${x.chars} chars)`).join(", ")} |`
      );
    }
    lines.push("");
    lines.push(
      "**Fix:** raise the role's context window (`TRANSLATE_CONTEXT_WINDOW`), lower " +
        "`TRANSLATE_CHUNK_CHARS` so chapters are split sooner, or shrink the reference artifact."
    );
    lines.push("");
  }
  return lines.join("\n");
}

// ─── Task entry ─────────────────────────────────────────────────────────────


module.exports = {
  buildQaRow,
  buildQaReportMarkdown,
};
